holonomic_robot: true
#heading_lookahead: 0.3
#heading_scoring: true
dwa: true

acc_lim_th: 3.2
acc_lim_x: 2.5
acc_lim_y: 2.5

max_vel_x: 0.45
min_vel_x: 0.1

max_vel_y: 0.1
min_vel_y: -0.1

max_trans_vel: 0.45
min_trans_vel: 0.05

max_rot_vel: 1.0
min_rot_vel: 0.25

sim_time: 1.0
sim_granularity: 0.05

goal_distance_bias: 0.8
path_distance_bias: 0.6
occdist_scale: 0.01

stop_time_buffer: 0.2
oscillation_reset_dist: 0.05

forward_point_distance: 0.325

scaling_speed: 0.25
max_scaling_factor: 0.2

vx_samples: 3
vy_samples: 7
vtheta_samples: 16
sim_period: 0.1

xy_goal_tolerance: 0.15
yaw_goal_tolerance: 0.05

rot_stopped_vel: 0.01
trans_stopped_vel: 0.01


