{auto_exposure: false, auto_gain: false, auto_whitebalance: false, exposure: 0.25,
  frame_id: high_def_optical_frame, gain: 0, height: 0, trigger_mode: streaming, whitebalance_blue: 300,
  whitebalance_red: 120, width: 0, x_offset: 0, y_offset: 0}
