auto_black_level: false
auto_exposure: false
auto_exposure_alternate: false
auto_gain: false
auto_gain_alternate: true
black_level: -127
black_level_filter_length: 7
black_level_step_size: 26
brightness: 1
camera_url: name://forearm_l#lan1@10.69.0.42
companding: true
companding_alternate: true
exposure: 0.0060000000000000001
exposure_alternate: 0.040000000000000001
ext_trig: false
first_packet_offset: 0.0025000000000000001
frame_id: l_forearm_cam_optical_frame
gain: 124
gain_alternate: 93
height: 480
horizontal_binning: 1
image_color:
  compressed: {format: jpeg, jpeg_quality: 80, png_level: 9}
  theora: {keyframe_frequency: 64, optimize_for: 1, quality: 31, target_bitrate: 800000}
image_color_rotated:
  compressed: {format: jpeg, jpeg_quality: 80, png_level: 9}
  theora: {keyframe_frequency: 64, optimize_for: 1, quality: 31, target_bitrate: 800000}
image_mono:
  compressed: {format: jpeg, jpeg_quality: 80, png_level: 9}
  theora: {keyframe_frequency: 64, optimize_for: 1, quality: 31, target_bitrate: 800000}
image_proc_debayer: {debayer: 0}
image_proc_rectify_color: {interpolation: 1}
image_proc_rectify_mono: {interpolation: 1}
image_raw:
  compressed: {format: jpeg, jpeg_quality: 80, png_level: 9}
  theora: {keyframe_frequency: 64, optimize_for: 1, quality: 31, target_bitrate: 800000}
image_rect:
  compressed: {format: jpeg, jpeg_quality: 80, png_level: 9}
  theora: {keyframe_frequency: 64, optimize_for: 1, quality: 31, target_bitrate: 800000}
image_rect_color:
  compressed: {format: jpeg, jpeg_quality: 80, png_level: 9}
  theora: {keyframe_frequency: 64, optimize_for: 1, quality: 31, target_bitrate: 800000}
imager_rate: 30.0
max_exposure: 0.036999999999999998
mirror_x: false
mirror_y: false
packet_debug: false
register_set: 0
rising_edge_trig: true
rotate_180: true
test_pattern: false
trig_rate: 30.0
trig_timestamp_topic: not_set
vertical_binning: 1
width: 640
x_offset: 0
y_offset: 0
